import {test,expect} from '@playwright/test';
test('evidence to planned decision, persistence, export and undo',async({page})=>{
await page.goto('./');await page.getByLabel('Select F01',{exact:true}).check();await page.getByLabel('Select F02',{exact:true}).check();await page.getByRole('button',{name:'Group selected (2)'}).click();await expect(page.getByText('Linked group F01')).toHaveCount(2);
await page.getByLabel('Suggested tag').fill('Import recovery');await page.getByRole('button',{name:'Accept reviewed tag'}).click();await page.getByLabel('Review status').selectOption('Planned');await page.reload();await expect(page.getByLabel('Suggested tag')).toHaveValue('Import recovery');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export shortlist'}).click();expect((await download).suggestedFilename()).toContain('shortlist.csv');
await page.getByRole('link',{name:/Product shortlist/}).click();await expect(page.locator('.feedback')).toHaveCount(1);await page.getByLabel('Review status').selectOption('Declined');await expect(page.locator('.feedback')).toHaveCount(0);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.feedback')).toHaveCount(1);
});
test('a planning decision does not require tag review',async({page})=>{await page.goto('./');await page.getByLabel('Review status').selectOption('Planned');await expect(page.getByLabel('Review status')).toHaveValue('Planned');await page.reload();await expect(page.getByLabel('Suggested tag')).toHaveValue('Onboarding');await expect(page.getByRole('button',{name:'Accept reviewed tag'})).toBeVisible();});
test('does not group a signal that a filter has hidden',async({page})=>{await page.goto('./');await page.getByLabel('Select F01',{exact:true}).check();await page.getByLabel('Select F02',{exact:true}).check();await page.getByLabel('Search feedback',{exact:true}).fill('exactly where');const group=page.getByRole('button',{name:'Group selected (1)'});await expect(group).toBeDisabled();await page.getByLabel('Search feedback',{exact:true}).fill('');await expect(page.getByRole('button',{name:'Group selected (2)'})).toBeEnabled();});
test('shows the filtered signal in the detail panel',async({page})=>{await page.goto('./');await page.getByLabel('Search feedback',{exact:true}).fill('weekly operations report');const detail=page.getByRole('region',{name:'Feedback detail'});await expect(detail.getByRole('heading',{name:'Save the weekly operations report'})).toBeVisible();await expect(detail.getByRole('heading',{name:'Show exactly where an import failed'})).toHaveCount(0);});
test('mobile search and unavailable storage',async({page})=>{await page.setViewportSize({width:390,height:844});await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}}));await page.goto('./');await expect(page.getByRole('status')).toContainText('unavailable');await page.getByLabel('Search feedback',{exact:true}).fill('not found');await expect(page.getByText('No matching feedback')).toBeVisible();await page.getByRole('button',{name:'Clear filters'}).click();await expect(page.locator('.feedback')).toHaveCount(6);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
