export const states = ['Inbox','Reviewing','Planned','Declined'] as const;
export const segments = ['Starter','Growth','Enterprise'] as const;
export type Status = typeof states[number];
export type Feedback = {id:string;title:string;quote:string;segment:string;accounts:string[];source:string;tag:string;reviewed:boolean;impact:number;confidence:number;effort:number;status:Status;rationale:string;group:string|null};
const hasText=(value:unknown):value is string=>typeof value==='string'&&value.trim().length>0;
export const seed:Feedback[] = [
{id:'F01',title:'Show exactly where an import failed',quote:'We restarted the entire customer import after a single invalid row. I need to fix the row, not repeat my afternoon.',segment:'Growth',accounts:['Alder Labs','Finch Studio','Cedar Systems'],source:'Support interview example',tag:'Onboarding',reviewed:false,impact:4,confidence:0.8,effort:3,status:'Inbox',rationale:'Three accounts describe the same blocked onboarding step. Validate frequency before committing.',group:null},
{id:'F02',title:'Retry failed rows without starting over',quote:'Our administrator cannot tell which rows were rejected. Can we download a list of errors?',segment:'Enterprise',accounts:['Pineworks','Alder Labs'],source:'Customer success example',tag:'Onboarding',reviewed:false,impact:4,confidence:0.8,effort:3,status:'Inbox',rationale:'Likely overlaps the import recovery request. Preserve both original accounts.',group:null},
{id:'F03',title:'Make permission changes easier to audit',quote:'When a workspace role changes, I need to explain who approved access to our operations team.',segment:'Enterprise',accounts:['Pineworks','Harbor Group'],source:'Sales call example',tag:'Administration',reviewed:false,impact:5,confidence:0.6,effort:5,status:'Reviewing',rationale:'Important for larger accounts, but evidence comes from a small sample.',group:null},
{id:'F04',title:'Save the weekly operations report',quote:'Every Monday I rebuild the same report filters. A saved view would remove a repetitive step.',segment:'Growth',accounts:['Finch Studio','Cedar Systems','Marble Co','Alder Labs'],source:'In-product example',tag:'Reporting',reviewed:false,impact:3,confidence:0.8,effort:2,status:'Inbox',rationale:'Repeated workflow with broad reach. Check whether saved filters are enough.',group:null},
{id:'F05',title:'Give new teammates a shorter first checklist',quote:'I saw twelve setup tasks before I understood what Northstar did. Which two get me to my first useful result?',segment:'Starter',accounts:['Birch Works','Juniper Team'],source:'Usability example',tag:'Onboarding',reviewed:false,impact:4,confidence:0.6,effort:2,status:'Inbox',rationale:'Prioritize first value over more configuration. Needs observed usability sessions.',group:null},
{id:'F06',title:'Customize every button color',quote:'Our team would like the workspace to match our internal brand palette.',segment:'Starter',accounts:['Juniper Team'],source:'Support example',tag:'Personalization',reviewed:true,impact:1,confidence:0.4,effort:3,status:'Declined',rationale:'Defer while first-value and reliability problems remain unresolved.',group:null}
];
export function normalizeEffort(value:number){return Number.isFinite(value)?Math.min(100,Math.max(.5,value)):.5;}
export function uniqueAccounts(accounts:string[]){const seen=new Set<string>();return accounts.map(account=>account.trim()).filter(account=>{const key=account.toLowerCase();if(!account||seen.has(key))return false;seen.add(key);return true;});}
export function newFeedbackId(items:Feedback[],timestamp=Date.now()){const base=`F${timestamp}`;const used=new Set(items.map(item=>item.id.toLowerCase()));let candidate=base;let suffix=2;while(used.has(candidate.toLowerCase()))candidate=`${base}-${suffix++}`;return candidate;}
export function score(item:Feedback){return Math.round(uniqueAccounts(item.accounts).length * item.impact * item.confidence / Math.max(.5,item.effort)*10)/10;}
export function merge(items:Feedback[],ids:string[]){const selected=[...new Set(ids)].filter(id=>items.some(item=>item.id===id));if(selected.length<2)return items;const linkedGroups=new Set(items.filter(item=>selected.includes(item.id)&&item.group).map(item=>item.group));const memberIds=new Set(items.filter(item=>selected.includes(item.id)||(item.group!==null&&linkedGroups.has(item.group))).map(item=>item.id));const group=selected[0];return items.map(item=>memberIds.has(item.id)?{...item,group}:item);}
export function groupAccounts(items:Feedback[],item:Feedback){return uniqueAccounts(items.filter(i=>item.group?i.group===item.group:i.id===item.id).flatMap(i=>i.accounts));}
export function csv(items:Feedback[]){const cell=(s:unknown)=>{const value=typeof s==='string'&&/^[\t\r\n ]*[=+\-@]/.test(s)?"'"+s:String(s);return '"'+value.replace(/"/g,'""')+'"';};const planned=items.filter(i=>i.status==='Planned').sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id));return [['ID','Title','Status','Original record accounts','Directional score','Effort estimate','Decision rationale'],...planned.map(i=>[i.id,i.title,i.status,uniqueAccounts(i.accounts).join('; '),score(i),i.effort,i.rationale])].map(row=>row.map(cell).join(',')).join('\n');}
export function isFeedback(value:unknown):value is Feedback{if(!value||typeof value!=='object')return false;const i=value as Partial<Feedback>;return typeof i.id==='string'&&hasText(i.title)&&hasText(i.quote)&&segments.includes(i.segment as typeof segments[number])&&hasText(i.source)&&typeof i.tag==='string'&&typeof i.reviewed==='boolean'&&typeof i.rationale==='string'&&Array.isArray(i.accounts)&&i.accounts.length>0&&i.accounts.every(hasText)&&states.includes(i.status as Status)&&typeof i.impact==='number'&&i.impact>=1&&i.impact<=5&&typeof i.confidence==='number'&&[.4,.6,.8,1].includes(i.confidence)&&typeof i.effort==='number'&&Number.isFinite(i.effort)&&i.effort>=.5&&(i.group===null||typeof i.group==='string');}
export function isFeedbackList(value:unknown):value is Feedback[]{if(!Array.isArray(value)||!value.length||!value.every(isFeedback))return false;const ids=new Set(value.map(item=>item.id.trim()));const normalizedIds=new Set(value.map(item=>item.id.trim().toLowerCase()));if(ids.size!==value.length||normalizedIds.size!==value.length||[...ids].some(id=>!id))return false;return value.every(item=>item.group===null||(ids.has(item.group)&&value.filter(candidate=>candidate.group===item.group).length>=2));}
