import {it,expect} from 'vitest';
import {csv,isFeedback,isFeedbackList,seed} from './model';
import {readSavedFeedback} from './storage';
it('neutralizes spreadsheet formula text in exported user fields',()=>{for(const title of ['=2+2','+CMD','-1+2','@SUM(1)','\t=2+2'])expect(csv([{...seed[0],title,status:'Planned'}])).toContain("'"+title);});
it('rejects incomplete persisted feedback records',()=>{expect(isFeedback({id:'F1',title:'x',accounts:[],status:'Inbox',effort:1,quote:'q'})).toBe(false);expect(isFeedback(seed[0])).toBe(true);});
it('rejects saved feedback without usable evidence context',()=>{for(const patch of [{title:' '},{quote:''},{accounts:[]},{accounts:['  ']}])expect(isFeedback({...seed[0],...patch})).toBe(false);});
it('rejects persisted effort outside the review control range',()=>{expect(isFeedback({...seed[0],effort:100.5})).toBe(false);});
it('rejects persisted impact values outside the integer review control',()=>{expect(isFeedback({...seed[0],impact:3.5})).toBe(false);});
it('rejects saved feedback outside the visible segment vocabulary',()=>{expect(isFeedback({...seed[0],segment:'Strategic'})).toBe(false);});
it('rejects duplicate ids and incomplete saved groups',()=>{expect(isFeedbackList(seed)).toBe(true);expect(isFeedbackList([seed[0],{...seed[1],id:'F01'}])).toBe(false);expect(isFeedbackList([{...seed[0],group:'F01'},...seed.slice(1)])).toBe(false);});
it('rejects saved ids that collide after normalization',()=>{expect(isFeedbackList([seed[0],{...seed[1],id:' f01 '}])).toBe(false);});
it('rejects saved group references with ambiguous whitespace',()=>{expect(isFeedback({...seed[0],group:' F01'})).toBe(false);});
it('keeps incompatible persisted data blocked until an explicit reset',()=>{const result=readSavedFeedback(JSON.stringify([{id:'broken'}]));expect(result.items).toEqual(seed);expect(result.blocked).toBe(true);expect(readSavedFeedback(JSON.stringify(seed)).blocked).toBe(false);});
it('returns an isolated sample when storage is empty',()=>{const result=readSavedFeedback(null);result.items[0].accounts.push('Temporary test label');expect(seed[0].accounts).not.toContain('Temporary test label');});
it('exports each affected account once after trimming and case folding',()=>{const result=csv([{...seed[0],status:'Planned',accounts:[' Alder Labs','alder labs','Finch Studio ']}]);expect(result).toContain('Alder Labs; Finch Studio');expect(result).not.toContain('alder labs');});
